/**
 * MembershipRequest Resource
 *
 * Public application form for survivors who want to join the foundation.
 *
 * Endpoint surface (auto-generated by `defineResource`):
 *
 *   POST   /api/membership-requests       — public submission (anyone)
 *   GET    /api/membership-requests       — admin lists (filter by status)
 *   GET    /api/membership-requests/:id   — admin reads one
 *   PATCH  /api/membership-requests/:id   — admin sets status, rejectionReason,
 *                                           or `memberId` once a Member row exists
 *   DELETE /api/membership-requests/:id   — admin archives (soft)
 *
 * Frontend approval flow (single browser session):
 *   1. POST `/api/members` with the applicant's profile fields (admin-only)
 *      to create a directory entry. If the applicant should be able to log
 *      in, ALSO create a BA user (admin plugin's `createUser`) and pass
 *      its id as `userId` on the new member.
 *   2. PATCH this resource: `{ status: 'approved', memberId: <newMemberId> }`.
 *
 * Frontend rejection flow:
 *   PATCH `{ status: 'rejected', rejectionReason: '<why>' }` — done.
 */

import { defineResource } from '@classytic/arc';
import { allowPublic, requireRoles } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import MembershipRequest, { type IMembershipRequest } from './membership-request.model.js';
import membershipRequestRepository from './membership-request.repository.js';

const queryParser = new QueryParser({
  allowedFilterFields: [
    'status',
    'email',
    'division',
    'districtLabel',
    'traffickingType',
  ],
});

const membershipRequestResource = defineResource<IMembershipRequest>({
  name: 'membership-request',
  prefix: '/membership-requests',
  adapter: createMongooseAdapter({
    model: MembershipRequest,
    repository: membershipRequestRepository,
    schemaGenerator: buildCrudSchemasFromModel,
  }),
  queryParser,
  // Hard delete only — the `status` field encodes lifecycle; a deleted
  // application is one the admin wants gone for real.
  // Single-tenant: foundation-wide, no per-org scoping on the request.
  tenantField: false,

  permissions: {
    // Anyone can apply.
    create: allowPublic(),
    // Admin reviews + manages.
    list: requireRoles(['admin']),
    get: requireRoles(['admin']),
    update: requireRoles(['admin']),
    delete: requireRoles(['admin']),
  },

  schemaOptions: {
    fieldRules: {
      // Lock the audit trail to admin PATCH (`reviewedBy` / `reviewedAt`
      // are the only places we want server-stamped values; status flow
      // is admin-driven via PATCH).
      reviewedBy: { systemManaged: true },
      reviewedAt: { systemManaged: true },
    },
  },
});

export default membershipRequestResource;
