/**
 * Survivor Resource — member-recorded survivor master record.
 *
 * Endpoint surface (auto-generated by `defineResource` + `softDelete` preset):
 *
 *   POST   /api/survivors              — any signed-in member registers a survivor
 *   GET    /api/survivors              — list (members: own only; staff: all)
 *   GET    /api/survivors/:id          — read one by `ANB-SUR-…` (own/staff)
 *   PATCH  /api/survivors/:id          — edit (own/staff)
 *   DELETE /api/survivors/:id          — soft delete (own/staff)
 *   GET    /api/survivors/deleted      — staff list tombstones (softDelete preset)
 *   POST   /api/survivors/:id/restore  — restore a tombstone (softDelete preset)
 *   GET    /api/survivors/aggregations/byGender|byMonth|byRecorder — staff stats
 *
 * Ownership is enforced by `ownedOrStaff()` (members are transparently scoped
 * to `recordedBy === their userId`; staff bypass). `recordedBy` is stamped in
 * `beforeCreate` so the client can never spoof the owner.
 */

import { defineResource } from '@classytic/arc';
import { requireAuth } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { ownedOrStaff, requireStaff } from '#shared/permissions.js';
import Survivor, { type ISurvivor } from './survivor.model.js';
import survivorRepository from './survivor.repository.js';

const queryParser = new QueryParser({
  allowedFilterFields: ['gender', 'countryReturnedFrom', 'recordedBy'],
  // `regex` mode = $or regex across searchFields on the `?search=` param —
  // no MongoDB text index required (the FE survivor search relies on this).
  searchMode: 'regex',
  searchFields: ['name', 'mobile', 'address', 'survivorId'],
});

const survivorResource = defineResource<ISurvivor>({
  name: 'survivor',
  prefix: '/survivors',
  adapter: createMongooseAdapter({
    model: Survivor,
    repository: survivorRepository,
    schemaGenerator: buildCrudSchemasFromModel,
  }),
  queryParser,
  // Single-tenant foundation — ownership (not org tenancy) scopes reads.
  tenantField: false,
  presets: ['softDelete'],

  // Route :id binds to the friendly `survivorId` (`ANB-SUR-2026-0001`).
  idField: 'survivorId',

  permissions: {
    create: requireAuth(),
    list: ownedOrStaff(),
    get: ownedOrStaff(),
    update: ownedOrStaff(),
    delete: ownedOrStaff(),
  },

  hooks: {
    // Stamp the recording member server-side + sensible identification
    // defaults. `ctx.scope.userId` is the BA user id resolved by the arc
    // better-auth adapter; fall back to `ctx.user` for safety.
    beforeCreate: async (ctx) => {
      const uid = ctx.scope?.userId ?? ctx.user?.id ?? ctx.user?._id;
      const name =
        (ctx.user?.name as string | undefined) ?? (ctx.user?.email as string | undefined);
      if (uid) ctx.data.recordedBy = uid;
      if (name) ctx.data.recordedByName = name;
      // Identification defaults mirror the paper registrar — the recording
      // member is the identifier unless they typed someone else, and the
      // identification date defaults to today.
      if (!ctx.data.identifiedBy && name) ctx.data.identifiedBy = name;
      if (!ctx.data.identifiedDate) ctx.data.identifiedDate = new Date();
      return ctx.data;
    },
  },

  schemaOptions: {
    fieldRules: {
      survivorId: { systemManaged: true },
      recordedBy: { systemManaged: true },
      recordedByName: { systemManaged: true },
      deletedAt: { systemManaged: true },
      createdAt: { systemManaged: true },
      updatedAt: { systemManaged: true },
    },
  },

  // Admin dashboard stats. Member "my counts" come from the list endpoint's
  // pagination total (already scoped to them) — no member-facing aggregation.
  aggregations: {
    byGender: {
      groupBy: 'gender',
      measures: { count: 'count' },
      sort: { count: -1 },
      permissions: requireStaff(),
    },
    // Per-member "who registered how many" — groups by the stable user id
    // AND the snapshot name so the dashboard can label rows without a join.
    byRecorder: {
      groupBy: ['recordedBy', 'recordedByName'],
      measures: { count: 'count' },
      sort: { count: -1 },
      permissions: requireStaff(),
    },
    byMonth: {
      dateBuckets: { month: { field: 'identifiedDate', interval: 'month' } },
      measures: { count: 'count' },
      sort: { month: 1 },
      permissions: requireStaff(),
    },
  },
});

export default survivorResource;
