/**
 * Chapter Resource — admin CRUD for foundation chapters.
 *
 * Endpoint surface (auto-generated by `defineResource`):
 *
 *   GET    /api/chapters          — public list (drives the FE chapter picker)
 *   GET    /api/chapters/:id      — public read
 *   POST   /api/chapters          — admin create
 *   PATCH  /api/chapters/:id      — admin edit
 *   DELETE /api/chapters/:id      — admin remove (hard delete)
 *
 * Public reads are intentional: members are linked to chapters by id,
 * and the public `/members` + dashboard member sheet both need to
 * resolve the chapter name without an admin token. Writes stay admin.
 *
 * "Deactivate without deleting" is covered by `status: 'inactive'` —
 * no soft-delete tombstone needed.
 */

import { defineResource } from '@classytic/arc';
import { allowPublic } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { requireAdmin } from '#shared/permissions.js';
import Chapter, { type IChapter } from './chapter.model.js';
import chapterRepository from './chapter.repository.js';

const queryParser = new QueryParser({
  allowedFilterFields: ['status', 'division', 'districtLabel', 'leadMemberId'],
  searchFields: ['name', 'slug', 'districtLabel', 'description'],
});

const chapterResource = defineResource<IChapter>({
  name: 'chapter',
  prefix: '/chapters',
  adapter: createMongooseAdapter({
    model: Chapter,
    repository: chapterRepository,
    schemaGenerator: buildCrudSchemasFromModel,
  }),
  queryParser,
  // Single-tenant foundation — no per-org scoping. Every chapter
  // belongs to Anirban.
  tenantField: false,

  permissions: {
    list: allowPublic(),
    get: allowPublic(),
    create: requireAdmin(),
    update: requireAdmin(),
    delete: requireAdmin(),
  },

  schemaOptions: {
    fieldRules: {
      createdAt: { systemManaged: true },
      updatedAt: { systemManaged: true },
    },
  },
});

export default chapterResource;
