/**
 * Member Resource — public + admin directory of foundation members.
 *
 * Plain arc resource over a plain mongoose model. We deliberately moved
 * OFF Better Auth's `organization.member` overlay so:
 *
 *   1. Members can exist WITHOUT a BA `user` row (`userId` optional) —
 *      the public directory carries survivor profiles, ambassadors,
 *      alumni who don't need to log in. Email is optional too.
 *   2. Admins create entries with a single `POST /api/members` — no
 *      invite-then-accept dance for directory-only people.
 *   3. arc auto-generates the full CRUD surface; mongokit's QueryParser
 *      auto-derives the safe filter operators per whitelisted field.
 *
 * Auth + roles still live in BA: the `user.role` field carries the
 * foundation role (`admin | committee_member | general`) via BA's admin
 * plugin, and arc's auth adapter populates `request.scope.userRoles`
 * from it. `requireRoles(['admin'])` therefore works without any
 * org-context plumbing.
 *
 * Endpoint surface (auto-generated by `defineResource`):
 *
 *   GET    /api/members          — public listing with filter/search/pagination
 *   GET    /api/members/:id      — public single read
 *   POST   /api/members          — admin creates a directory entry
 *   PATCH  /api/members/:id      — admin or owning user (userId match) updates
 *   DELETE /api/members/:id      — admin removes (hard delete)
 *
 * FE filter examples:
 *   /api/members?division=BDA&memberStatus=active
 *   /api/members?division[in]=BDA,BDB,BDC
 *   /api/members?team=executive_committee&sort=teamRank
 *   /api/members?isPubliclyListed=true&sort=-joinedAt
 *   /api/members?q=anjali (free-text — see `searchFields` below)
 */

import type { FastifyReply, FastifyRequest } from 'fastify';
import { defineResource } from '@classytic/arc';
import { allowPublic, anyOf, requireOwnership } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { requireAdmin } from '#shared/permissions.js';
import { getFoundationSummary } from '#shared/foundation-stats.js';
import Member, { type IMember } from './member.model.js';
import memberRepository from './member.repository.js';

const queryParser = new QueryParser({
  // Whitelisted fields — QueryParser auto-applies the safe operator
  // suite ([eq], [in], [ne], [contains], …) per field.
  allowedFilterFields: [
    'userId',
    'email',
    'role',
    'memberStatus',
    'division',
    'districtLabel',
    'roleLabel',
    'isPubliclyListed',
    'team',
    'gender',
    'age',
    'chapterId',
    'isChapterLead',
  ],
  // Free-text search — `?q=anjali` runs case-insensitive across these
  // fields (auto mode: text index when present, $or-of-$regex fallback).
  searchFields: ['displayName', 'districtLabel', 'roleLabel', 'bio', 'tags', 'teamPosition'],
});

const memberResource = defineResource<IMember>({
  name: 'member',
  prefix: '/members',
  adapter: createMongooseAdapter({
    model: Member,
    repository: memberRepository,
    schemaGenerator: buildCrudSchemasFromModel,
  }),
  queryParser,
  // No soft-delete preset — DELETE physically removes the row. See the
  // repository file for rationale.
  // Single-tenant: foundation-wide. Marketing site reads everyone's
  // public profiles; no per-row org scoping.
  tenantField: false,

  permissions: {
    list: allowPublic(),
    get: allowPublic(),
    create: requireAdmin(),
    // Admin / superadmin can edit anyone; a logged-in user can edit their
    // own row (matched by `userId`).
    update: anyOf(requireAdmin(), requireOwnership('userId')),
    delete: requireAdmin(),
  },

  schemaOptions: {
    fieldRules: {
      // Bookkeeping — server stamps these.
      createdAt: { systemManaged: true },
      updatedAt: { systemManaged: true },
    },
  },

  // ─── Custom routes ─────────────────────────────────────────────────
  // Public foundation summary in a single response: total members, total
  // chapters, distinct divisions and districts, gender breakdown. Drives
  // the marketing hero stats on /members and /about with ONE fetch
  // (instead of N parallel groupBy calls composed on the FE).
  //
  // Logic lives in the dedicated stats service so the route handler
  // stays a thin glue layer and the same code can serve dashboard cards
  // later without duplication.
  routes: [
    {
      method: 'GET',
      path: '/summary',
      summary: 'Public foundation stats summary (cross-resource).',
      permissions: allowPublic(),
      // `raw: true` gives us the Fastify req/reply directly. Without it,
      // arc's auto-wrap layer dropped the return value as an empty body.
      raw: true,
      handler: async (_req: FastifyRequest, reply: FastifyReply) => {
        const summary = await getFoundationSummary();
        return reply.code(200).send(summary);
      },
    },
  ],
});

export default memberResource;
