/**
 * Member Resource — public + admin directory of foundation members.
 *
 * Plain arc resource over a plain mongoose model. We deliberately moved
 * OFF Better Auth's `organization.member` overlay so:
 *
 *   1. Members can exist WITHOUT a BA `user` row (`userId` optional) —
 *      the public directory carries survivor profiles, ambassadors,
 *      alumni who don't need to log in. Email is optional too.
 *   2. Admins create entries with a single `POST /api/members` — no
 *      invite-then-accept dance for directory-only people.
 *   3. arc auto-generates the full CRUD surface; mongokit's QueryParser
 *      auto-derives the safe filter operators per whitelisted field.
 *
 * Auth + roles still live in BA: the `user.role` field carries the
 * foundation role (`admin | committee_member | general`) via BA's admin
 * plugin, and arc's auth adapter populates `request.scope.userRoles`
 * from it. `requireRoles(['admin'])` therefore works without any
 * org-context plumbing.
 *
 * Endpoint surface (auto-generated by `defineResource`):
 *
 *   GET    /api/members          — public listing with filter/search/pagination
 *   GET    /api/members/:id      — public single read
 *   POST   /api/members          — admin creates a directory entry
 *   PATCH  /api/members/:id      — admin or owning user (userId match) updates
 *   DELETE /api/members/:id      — admin removes (soft-delete via preset)
 *
 * FE filter examples:
 *   /api/members?division=BDA&memberStatus=active
 *   /api/members?division[in]=BDA,BDB,BDC
 *   /api/members?team=executive_committee&sort=teamRank
 *   /api/members?isPubliclyListed=true&sort=-joinedAt
 *   /api/members?q=anjali (free-text — see `searchFields` below)
 */

import { defineResource } from '@classytic/arc';
import { allowPublic, anyOf, requireOwnership, requireRoles } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import Member, { type IMember } from './member.model.js';
import memberRepository from './member.repository.js';

const queryParser = new QueryParser({
  // Whitelisted fields — QueryParser auto-applies the safe operator
  // suite ([eq], [in], [ne], [contains], …) per field.
  allowedFilterFields: [
    'userId',
    'email',
    'role',
    'memberStatus',
    'division',
    'districtLabel',
    'roleLabel',
    'isPubliclyListed',
    'team',
  ],
  // Free-text search — `?q=anjali` runs case-insensitive across these
  // fields (auto mode: text index when present, $or-of-$regex fallback).
  searchFields: ['displayName', 'districtLabel', 'roleLabel', 'bio', 'tags', 'teamPosition'],
});

const memberResource = defineResource<IMember>({
  name: 'member',
  prefix: '/members',
  adapter: createMongooseAdapter({
    model: Member,
    repository: memberRepository,
    schemaGenerator: buildCrudSchemasFromModel,
  }),
  queryParser,
  presets: ['softDelete'],
  // Single-tenant: foundation-wide. Marketing site reads everyone's
  // public profiles; no per-row org scoping.
  tenantField: false,

  permissions: {
    list: allowPublic(),
    get: allowPublic(),
    create: requireRoles(['admin']),
    // Admin can edit anyone; a logged-in user can edit their own row
    // (matched by `userId`).
    update: anyOf(requireRoles(['admin']), requireOwnership('userId')),
    delete: requireRoles(['admin']),
  },

  schemaOptions: {
    fieldRules: {
      // Bookkeeping — server stamps these.
      createdAt: { systemManaged: true },
      updatedAt: { systemManaged: true },
    },
  },
});

export default memberResource;
