/**
 * Member Resource — public + admin directory over BA's `member` collection.
 *
 * Better Auth's `organization` plugin owns the `member` collection
 * end-to-end (writes via `auth.api.inviteMember` → accept-invitation,
 * role updates via `updateMemberRole`, removal via `removeMember`). We
 * don't define a parallel mongoose model. Instead we use mongokit's
 * `createBetterAuthOverlay` to register ONE typed mongoose model on
 * BA's collection — driven by the resolved schema BA already publishes
 * on `auth.$context.tables.member`. Every additional field we declared
 * in `auth.config.ts` (`division`, `districtLabel`, `bio`, `tags`,
 * `memberStatus`, ...) flows through automatically.
 *
 * Endpoints (auto-generated by `defineResource`):
 *
 *   GET   /api/members           — public listing with filter/search/pagination
 *                                  via mongokit's QueryParser
 *   GET   /api/members/:id       — public single read
 *   PATCH /api/members/:id       — admin-only — fill in profile fields
 *                                  BA doesn't own (`displayName`, `bio`,
 *                                  `division`, `districtLabel`, `tags`...)
 *
 *   POST + DELETE                — disabled. Membership creation lives in
 *                                  BA's invite-member → accept-invitation
 *                                  flow; removal via `auth.api.removeMember`.
 *
 * FE filter examples:
 *   /api/members?division=BDA&memberStatus=active
 *   /api/members?division[in]=BDA,BDB,BDC
 *   /api/members?isPubliclyListed=true&sort=-joinedAt
 *   /api/members?q=anjali (free-text — see `searchableFields` below)
 */

import mongoose from 'mongoose';
import { defineResource } from '@classytic/arc';
import { allowPublic, anyOf, requireOwnership, requireRoles } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createBetterAuthOverlay } from '@classytic/mongokit/better-auth';
import { getAuth } from '#resources/auth/auth.config.js';

// Top-level await: `createBetterAuthOverlay` reads BA's resolved schema
// (`auth.$context.tables.member`) and `getAuth()` requires an open
// mongoose connection. Both are satisfied because arc imports each
// `*.resource.ts` via `loadResources` during the registerResources phase
// — i.e. AFTER `bootstrap[]` (mongoose connected, foundation org seeded).
// The default export below is the resolved `ResourceDefinition` arc
// registers — same shape as a synchronous resource module, so the
// `loadResources` discovery util and any consumer reading
// `import memberResource from './member/member.resource.js'` both work.
//
// `getAuth()` is narrowed to the `{ handler, api }` shape arc needs.
// `createBetterAuthOverlay` also reads `$context` (present at runtime,
// elided at the narrow type) — the cast threads through.
const adapter = await createBetterAuthOverlay({
  auth: getAuth() as never,
  mongoose,
  collection: 'member',
  schemaGenerator: buildCrudSchemasFromModel,
});

const queryParser = new QueryParser({
  // Whitelist the fields the directory needs to filter by. mongokit's
  // QueryParser auto-applies safe operators ([eq], [in], [ne],
  // [contains] etc) per field.
  allowedFilterFields: [
    'userId',
    'division',
    'memberStatus',
    'roleLabel',
    'isPubliclyListed',
    'organizationId',
    'role',
  ],
  // Free-text search — `?q=anjali` runs a case-insensitive regex match
  // across these fields (QueryParser uses 'auto' mode: text index when
  // present, $or-of-$regex fallback otherwise — fine for our scale).
  searchFields: ['displayName', 'districtLabel', 'roleLabel', 'bio', 'tags'],
});

const memberResource = defineResource({
  name: 'member',
  prefix: '/members',
  adapter,
  queryParser,
  // Single-tenant: foundation-wide. The marketing site reads everyone's
  // public profiles, so no per-row org scoping at the resource level.
  tenantField: false,

  // Membership creation + removal flow through BA. We expose only
  // GET (public) + PATCH (admin) — the brand-facing profile edit.
  disabledRoutes: ['create', 'delete'],

  permissions: {
    list: allowPublic(),
    get: allowPublic(),
    // Admin can edit anyone; member can edit their own record (userId match).
    update: anyOf(requireRoles(['admin']), requireOwnership('userId')),
  },

  schemaOptions: {
    fieldRules: {
      // Authoritative BA fields — never accept these via PATCH; BA owns them.
      organizationId: { systemManaged: true },
      userId: { systemManaged: true },
      role: { systemManaged: true },
      // Bookkeeping — system-stamped.
      createdAt: { systemManaged: true },
      updatedAt: { systemManaged: true },
    },
  },
});

export default memberResource;
