/**
 * anirban-be - App Factory
 * Generated by Arc CLI
 *
 * Creates and configures the Fastify app instance.
 * Can be imported by:
 * - index.ts (HTTP server via app.listen, or edge handler via toFetchHandler)
 * - worker.ts (background workers)
 * - tests (integration tests via app.inject)
 */

import type { FastifyInstance } from 'fastify';
import type { ResourceLike } from '@classytic/arc/factory';
import config from '#config/index.js';
import { createApp } from '@classytic/arc/factory';
import { createBetterAuthAdapter } from '@classytic/arc/auth';
import { getAuth } from '#resources/auth/auth.config.js';

// App-specific plugins
import { registerPlugins } from '#plugins/index.js';

interface CreateAppInstanceOptions {
  /**
   * Explicit resources override — bypasses `resourceDir` discovery.
   * Tests pass `STATIC_RESOURCES` from `#resources/index.js` because
   * vitest's tsx loader can't follow nested `.js`→`.ts` resolution
   * through `loadResources`'s dynamic imports. Per arc's contract,
   * "explicit `resources` wins over `resourceDir`."
   */
  resources?: ReadonlyArray<ResourceLike>;
}

/**
 * Create a fully configured app instance
 *
 * @returns Configured Fastify instance ready to use
 */
export async function createAppInstance(
  options: CreateAppInstanceOptions = {},
): Promise<FastifyInstance> {
  // Create Arc app with resources and base configuration. `resourcePrefix`
  // mounts every resource under `/api`, matching the `apiPrefix` the
  // OpenAPI plugin advertises — without it the docs and the actual routes
  // would disagree (CLI scaffold gap).
  const app = await createApp({
    preset: config.env === 'production' ? ('production') : 'development',
    // Production / dev: auto-discover every `*.resource.ts` under
    // `src/resources/` via arc's `loadResources`. Imports run during
    // the resources phase (AFTER `bootstrap[]`), so resource modules
    // with top-level await against the BA / mongoose context resolve
    // cleanly. The URL form works in both `src/` (tsx) and `dist/`
    // (built) without path gymnastics.
    //
    // Tests bypass discovery by passing `options.resources` — vitest's
    // tsx loader chokes on `loadResources`'s dynamic-import +
    // nested-`.js` chain.
    ...(options.resources
      ? { resources: options.resources as ResourceLike[] }
      : { resourceDir: import.meta.url }),
    resourcePrefix: '/api',
    auth: {
      type: 'betterAuth',
      // `orgContext: true` makes arc resolve `req.scope.orgRoles` from
      // BA's `member` collection — required when resource permissions
      // call `requireRoles` (which checks BA org-roles, not just the
      // platform user role). Without it every authenticated request lands
      // as `kind: 'authenticated'` and admin-only endpoints 403.
      betterAuth: createBetterAuthAdapter({ auth: getAuth(), orgContext: true }),
    },
    cors: {
      origin: config.cors.origins,
      methods: config.cors.methods,
      allowedHeaders: config.cors.allowedHeaders,
      credentials: config.cors.credentials,
    },
    trustProxy: true,
    arcPlugins: {
      metrics: config.env === 'production',  // Prometheus /_metrics endpoint
    },
  });

  // Register app-specific plugins (explicit dependency injection)
  await registerPlugins(app, { config });

  return app;
}

export default createAppInstance;
