/**
 * anirban-be - Server Entry Point
 * Generated by Arc CLI
 *
 * This file starts the HTTP server.
 * For workers or other entry points, import createAppInstance from './app.js'
 */

// Load environment FIRST (before any other imports)
import '#config/env.js';

import config from '#config/index.js';
import mongoose from 'mongoose';
import {
  ensureBootstrapAdmin,
  ensureFoundationOrg,
} from '#resources/auth/bootstrap.js';
import { createAppInstance } from './app.js';

async function main(): Promise<void> {
  console.log(`Environment: ${config.env}`);

  // Connect to MongoDB
  await mongoose.connect(config.database.uri);
  console.log('Connected to MongoDB');

  // Seed the single foundation org + (optionally) the initial superadmin
  // BEFORE building the app — actions in resources read the foundation
  // org id at request time, so it must be cached up-front.
  const orgId = await ensureFoundationOrg();
  await ensureBootstrapAdmin(orgId);

  // Create and configure app
  const app = await createAppInstance();

  // Start server
  await app.listen({ port: config.server.port, host: config.server.host });
  console.log(`Server running at http://${config.server.host}:${config.server.port}`);
}

main().catch((err) => {
  console.error('Failed to start server:', err);
  process.exit(1);
});
