/**
 * Media Resource — Cloudinary-backed media library.
 *
 * Endpoint surface (auto-generated by `defineResource`):
 *
 *   GET    /api/media          — list (admin only)
 *   GET    /api/media/:id      — single read (admin only)
 *   PATCH  /api/media/:id      — edit alt text (admin only)
 *   POST   /api/media/upload   — upload a new asset (admin only)
 *   POST   /api/media/bulk-delete — bulk delete + storage cleanup (admin only)
 *
 * `create` is intentionally disabled — uploads go through the dedicated
 * `/upload` route because they carry a base64-encoded image body that
 * arc's auto-generated POST handler won't understand. `delete` is also
 * disabled at the route level so admins always go through `/bulk-delete`
 * (which calls the repo's `hardDeleteMany` → cleanup at Cloudinary
 * alongside the DB row).
 */

import type { FastifyRequest, FastifyReply } from 'fastify';
import {
  BaseController,
  defineResource,
  NotFoundError,
  ValidationError,
  type IControllerResponse,
  type IRequestContext,
} from '@classytic/arc';
import { requireAdmin } from '#shared/permissions.js';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import type { Repository } from '@classytic/mongokit';
import type { MediaRepository } from '@classytic/media-kit';
import { ensureMediaEngine } from './media.engine.js';

/**
 * `delete` on the base controller only removes the Mongo row; the storage
 * driver keeps the underlying Cloudinary asset. Override so admin DELETE
 * also fires the driver's `delete()` — matches the bulk-delete route's
 * cleanup semantics.
 */
class MediaController extends BaseController {
  private readonly mediaRepo: MediaRepository;

  constructor(repo: MediaRepository) {
    super(repo as unknown as Repository);
    this.mediaRepo = repo;
  }

  async delete(
    req: IRequestContext,
  ): Promise<IControllerResponse<{ message: string; id: string }>> {
    const id = req.params?.id as string | undefined;
    if (!id) throw new ValidationError('ID parameter is required');

    const user = req.user as { id?: string } | undefined;
    const ok = await this.mediaRepo.hardDelete(id, { userId: user?.id });
    if (!ok) throw new NotFoundError('Media');
    return { data: { message: 'Media deleted', id } };
  }
}

const queryParser = new QueryParser({
  allowedFilterFields: ['folder', 'mimeType', 'provider', 'status'],
  searchFields: ['filename', 'alt', 'title', 'description'],
});

function getUserId(req: FastifyRequest): string | undefined {
  return (req as unknown as { user?: { id?: string } }).user?.id;
}

// Top-level await runs in arc's resources slot (after `plugins()` /
// `bootstrap[]`), so mongoose.connection is already live when the engine
// boots — mirrors how `member.resource.ts` wires its BA overlay.
const engine = await ensureMediaEngine();
const Media = engine.models.Media;
const repo = engine.repositories.media;
const controller = new MediaController(repo);

const mediaResource = defineResource({
    name: 'media',
    displayName: 'Media',
    prefix: '/media',

    adapter: createMongooseAdapter({
      model: Media,
      repository: repo as unknown as Repository,
      schemaGenerator: buildCrudSchemasFromModel,
    }),
    controller,
    queryParser,
    // Single-tenant — every media row is foundation-wide. No per-org scoping.
    tenantField: false,

    // Auto-generated POST /api/media is removed: a Media doc only makes
    // sense AFTER the file is written to Cloudinary and we have a `key`
    // and `url`. The custom `/upload` route below is the single legal
    // path to create a media record — disabling create prevents orphan
    // rows from a misconfigured client.
    disabledRoutes: ['create'],

    permissions: {
      list: requireAdmin(),
      get: requireAdmin(),
      update: requireAdmin(),
      delete: requireAdmin(),
    },

    schemaOptions: {
      fieldRules: {
        // Plugin-stamped; never accept from a PATCH body.
        key: { systemManaged: true },
        url: { systemManaged: true },
        provider: { systemManaged: true },
        status: { systemManaged: true },
        hash: { systemManaged: true },
        size: { systemManaged: true },
        width: { systemManaged: true },
        height: { systemManaged: true },
        variants: { systemManaged: true },
        createdAt: { systemManaged: true },
        updatedAt: { systemManaged: true },
      },
    },

    routes: [
      {
        method: 'POST',
        path: '/upload',
        summary: 'Upload an image to Cloudinary and persist its metadata',
        permissions: requireAdmin(),
        raw: true,
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const body = req.body as {
            image?: string;
            filename?: string;
            mimeType?: string;
            size?: number;
            alt?: string;
            /**
             * Logical folder — `members`, `gallery`, `passport-scans`, etc.
             * Combined with the engine's `anirban` prefix to produce
             * `anirban/<folder>/<id>-<filename>` as the Cloudinary
             * public_id. FE owns the canonical list (see
             * `features/media/folders.ts`).
             */
            folder?: string;
          };

          if (!body.image || !body.filename) {
            return reply
              .code(400)
              .send({ error: 'image (base64) and filename are required' });
          }

          try {
            const buffer = Buffer.from(body.image, 'base64');
            const doc = await repo.upload(
              {
                buffer,
                filename: body.filename,
                mimeType: body.mimeType ?? 'application/octet-stream',
                alt: body.alt,
                folder: body.folder,
                // We never want media-kit to generate derivative variants
                // — Cloudinary serves resized URLs on demand.
                skipProcessing: true,
              },
              { userId: getUserId(req) },
            );
            return reply.code(201).send(doc);
          } catch (err) {
            // media-kit throws plain `Error` for both client-side issues
            // (file type / size rejection in `validateFileHelper`) AND
            // upstream Cloudinary failures. Heuristic: if the message
            // looks like validation, surface a 400 so the admin sees a
            // helpful toast; otherwise treat as upstream (502).
            const message = err instanceof Error ? err.message : 'Upload failed';
            const isClientError = /file (type|size)|empty/i.test(message);
            return reply.code(isClientError ? 400 : 502).send({ error: message });
          }
        },
      },

      {
        method: 'POST',
        path: '/bulk-delete',
        summary: 'Delete multiple media records with Cloudinary cleanup',
        permissions: requireAdmin(),
        raw: true,
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const body = req.body as { ids?: string[] };
          const ids = body.ids ?? [];
          if (!ids.length) return reply.code(400).send({ error: 'ids[] required' });

          const result = await repo.hardDeleteMany(ids, { userId: getUserId(req) });
          const failed = result.failed ?? [];
          if (!failed.length) return reply.code(204).send();
          return reply.code(207).send({ success: result.success, failed });
        },
      },
    ],
});

export default mediaResource;
